joconde_sqlserver:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 'localhost'
      port: 1433
      database: 'joconde_staging'
      schema: 'staging'
      user: '{{ env_var("JOCONDE_IMPORT_USER") }}'
      password: '{{ env_var("JOCONDE_IMPORT_PWD") }}'
      trust_cert: true
      threads: 1
